---
require: []

chdir: /var/www/festivus/current/
pid: tmp/pids/thin.pid
log: log/thin.log

environment: production

address: 0.0.0.0
port: 4000
servers: 4
max_conns: 1024
timeout: 30
wait: 30
max_persistent_conns: 512

threaded: true
no-epoll: true
daemonize: true
onebyone: true
tag: festivus-thin
