source 'https://rubygems.org'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~>3.2.0'

gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 3.2.0'
gem 'sqlite3'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 1.2u'
gem "therubyracer"
gem "less-rails"
gem "twitter-bootstrap-rails"
gem "bootstrap-datetimepicker-rails"
gem "bson_ext"
gem 'haml'
gem 'haml-rails'
gem 'surveyor', '>= 1.4.0'
gem 'sidekiq'
gem 'slim', '>= 1.1.0'
gem 'sinatra', '>=1.3.0', require: nil
gem 'foreman'
gem 'google-analytics-rails'
gem 'thin'
gem 'highlight', require: 'simplabs/highlight'

group :development do
  gem 'hirb'
end

group :doc do
  # bundle exec rake doc:rails generates the API under doc/api.
  gem 'sdoc', require: false
end
